### ISSUE TITLE
what it does

### ISSUE THREAD

**Issue by laxman07** [Suleman-Elahi/TwitterAutoFavorite#1]
this is a test

**Comment by Suleman-Elahi** [comment]
It automatically favorites the tweets which have a specified hashtag in them.

**Comment by laxman07** [comment]
![elephantilovefreesoftware](https://user-images.githubusercontent.com/7590770/40700464-3c88abea-63f7-11e8-9252-f3d36e4e1585.gif)

**Comment by laxman07** [comment]
@Suleman-Elahi  do you love free software.

**Comment by laxman07** [comment]
hello... test
