### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by Arwa200** [Suleman-Elahi/TwitterAutoFavorite#2]
Hello,
Thank you for this tool, I am wondering if I want to use this feature for another account, 
s there any way to add it? 

I have tried with adding  "screen_name": "USERNAME", 
to key.py file but i do not know where to add it inside 
auth function
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)

as well as replace the id 
for s in twt:
    api.create_favorite(s.id)
    print(s.id)
print("Done!!!")

Thank you

**Comment by Suleman-Elahi** [comment]
Sorry for the delay.

This doesn't use your Username or password and you don't have to add anything in the auth function. just add your API credentials in keys.py file and you are done.

**Comment by Arwa200** [comment]
> Sorry for the delay.
> 
> This doesn't use your Username or password and you don't have to add anything in the auth function. just add your API credentials in keys.py file and you are done.

Thank you for your response 
I am asking if there is a way to use username because I have one API with 2 accounts since getting API approvable is little bit hard  " I'm looking for faster way for many users" if that even possible!

Thank you again

**Comment by Suleman-Elahi** [comment]
Okay..to the best of my knowledge, I don't think it is possible. If you want to use username and password so badly then you can go for automation via Selenium. You can see [this repository](https://github.com/gumdropsteve/twitter) and see how it works without API.
